name: Test, Build, and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            BRANCH_NAME="${BRANCH_NAME}"

            if [ "$BRANCH_NAME" = "main" ]; then
              cd /home/sabdahtb/projects/nx-fullstack
              git pull origin main
              docker compose up -d --build  # Deploy with Docker Compose
            else
              echo "Unknown branch: $BRANCH_NAME. Exiting."
              exit 1
            fi
          EOF
